@api_key = <api_key>
@ai_search_same = <ai_search_name>
@index_name = <index_name>
@api_version = 2023-10-01-Preview
@open_ai_endpoint = <open_ai_endpoint>
@open_ai_model = <open_ai_model>
@open_ai_key = <open_ai_key>


### Create Index
PUT https://{{ai_search_same}}.search.windows.net/indexes/{{index_name}}?api-version={{api_version}} HTTP/1.1
content-type: application/json
api-key: {{api_key}}

{   
  "name": "{{index_name}}",
  "fields": [
    {
      "name": "id",
      "type": "Edm.String",
      "key": true,
      "filterable": true,
      "analyzer": "keyword"
    },
    {
      "name": "content",
      "type": "Edm.String",
      "searchable": true,
      "filterable": true,
      "sortable": true,
      "retrievable": true
    },
    {
      "name": "content_vector",
      "type": "Collection(Edm.Single)",
      "searchable": true,
      "retrievable": true,
      "dimensions": 1536,
      "vectorSearchProfile": "vector-profile"
    }
  ],
  "vectorSearch": {
    "algorithms": [
      {
        "name": "hnsw-config",
        "kind": "hnsw",
        "hnswParameters": {
          "m": 4,
          "efConstruction": 400,
          "efSearch": 500,
          "metric": "cosine"
        }
      }
    ],
    "vectorizers": [
      {
        "name": "ada_vectorizer",
        "kind": "azureOpenAI",
        "azureOpenAIParameters": {
          "resourceUri": "{{open_ai_endpoint}}",
          "deploymentId": "{{open_ai_model}}",
          "apiKey": "{{open_ai_key}}"
        }
      }
    ],
    "profiles": [
      {
        "name": "vector-profile",
        "algorithm": "hnsw-config",
        "vectorizer": "ada_vectorizer"
      }
    ]
  }
}